= Doom Launcher

https://ci.appveyor.com/project/hobomaster22/doomlauncher[image:https://ci.appveyor.com/api/projects/status/github/hobomaster22/doomlauncher?branch=development&svg=true[Build status]]

Doom Launcher is a _Doom_ frontend that serves as a database for
all your _Doom_ engine games, custom WADs, PK3s, and source ports. 
Start having all your files in one place. For convenience, you can
download files from https://www.doomworld.com/idgames/[/idgames] in the
launcher, similar to https://www.quaddicted.com/tools/quake_injector[Quake Injector].

Doom Launcher is packed with features, including:

* Direct download and metadata update from /idgames (through API).
* Add mods by drag and drop (ZIP including WAD/PK3/DEH/TXT).
* Automatic scraping of title, author, release date and description
from the included textfile.
* Importing screenshots directly from the sourceport into the database.
* Maintaining demos and savegames (DSG and ZDS supported).
* Scans files for map lump names (e.g. E4M3, MAP20, STR20).
* Add any source ports to the database.
* Launch source ports with parameters specifically
configured for them.
* Add and preview launch parameters for selected
file(s).
* Selecting specific files within a ZIP file.
* Automatically load ZIP files when selecting an IWAD
or source port you have configured the file with.
* Tagging mods with custom unlimited colored tags.
* Shows play-statistics (killed monsters, collected items, play time).
Supported source ports includes ZDoom, PrBoom+, and CNDoom (Competition
Doom).
* Automatic daily database backups (SQLite database files).
* Create shortcuts to launch your favorite files.

Many more features are documented in the Help file. Please read that if
you have any concerns on some features or find out something you may not
be aware of.

Doom Launcher is written by Hobomaster22 in C# and requires .NET 4.5.
If you want to a report bug or suggest a feature, submit an issue to
the GitHub repository.

== Building Doom Launcher
To build Doom Launcher, download a copy of the repository and open up
the Solution file on Visual Studio. Currently Visual Studio 14 toolsets
can be used. From there you can make your changes and test them
before submitting your changes or tweaking the launcher with your
own personal preferences.

Doom Launcher currently supports Windows 7 or above. Older Windows
operating systems will not run Doom Launcher. Mac and Linux are
unsupported.

== Development Tools

SQLite Browser. Great tool for viewing and editing the DoomLauncher.sqlite database: 
https://sqlitebrowser.org/

SonarLint. A great code analysis extension for Visual Studio. Highly recommended and used for most of Doom Launcher's development:
https://www.sonarlint.org/visualstudio/

== Doom Launcher Links
GitHub Repository: https://github.com/hobomaster22/DoomLauncher

Doomworld Thread: https://www.doomworld.com/vb/doom-general/69346-doom-launcher-doom-frontend-database/

Realm667: https://realm667.com/index.php/en/kunena/doom-launcher 
