namespace DoomLauncher
{
    public enum GameFileFieldType
    {
        Filename,
        Title,
        Author,
        Description,
        ReleaseDate,
        GameFileID,
        LastPlayed,
        Downloaded,
        Map,
        SourcePortID,
        IWadID,
        Comments,
        Rating,
        SettingsMap,
        SettingsSkill,
        SettingsExtraParams,
        SettingsFiles,
        SettingsSpecificFiles,
        MapCount,
        MinutesPlayed,
        MD5,
        SettingsStat,
        SettingsFilesIWAD,
        SettingsFilesSourcePort,
        SettingsGameProfileID,
        SettingsSaved
    }
}
