using System;
using System.Windows.Forms;

namespace DoomLauncher
{
    public partial class StatsInfo : Form
    {
        public StatsInfo()
        {
            InitializeComponent();

            pbInfo1.Image = DoomLauncher.Properties.Resources.bon2b;

            lblZdoom.Text = "For all ZDoom based ports. Uses save games to parse statistics. This means statistics cannot be read for the last level of an episode. " +
                "Items and skill level are not available for ZDoom, Zandronum, and GZDoom pre-3.5.0. Statistics will be recorded when the game is saved or when an auto save is generated.";
            lblBoom.Text = "Uses the -levelstat parameter and parses the generated levelstat.txt. All statistics will be recorded when the game has exited.";
            lblChocolate.Text = "Uses the -statdump parameter and parses the generated stats.txt. All statistics will be recorded when the game has exited. ExM8 maps are only generated by CNDoom.";

            Stylizer.Stylize(this, DesignMode, StylizerOptions.SetupTitleBar);
        }

        private void btnOK_Click(object sender, EventArgs e)
        {
            Close();
        }
    }
}
